db1:
  development:
    host: 'localhost'
    adapter: 'postgresql'
    encoding: utf-8
    database: 'makersbnb_dev'

  test:
    host: 'localhost'
    adapter: 'postgresql'
    encoding: utf-8
    database: 'makersbnb_test'

  production:
    host: 'localhost'
    adapter: 'postgresql'
    encoding: utf-8
    database: 'makersbnb_prod'